### ISSUE TITLE
I'm creating TypeScript declarations for jasmine-matchers to add to DefinitelyTyped

### ISSUE THREAD

**Issue by Bartvds** [uxebu/jasmine-matchers#3]
I love jasmine and your jasmine-matcher, but I'm switching from vanilla javascript to TypeScript so I'd like some declarations for autosuggest and compile checks.

I didn't locate any community type declarations for `jasmine-matchers` on [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) yet, so I went ahead and made them myself.

As that is the community source for type files for popular javascript libraries I'm planning to commit the one I created as well but I'd like to let you know. I'll export some test as well as required by DefinitelyTyped.

I'm not releasing yet, but my development code and grunt are currently located in a branch fork of this repos: https://github.com/Bartvds/jasmine-matchers/blob/typings/typings/jasmine-matchers.d.ts

Note this is an add-on and doesn't have to be a merge.

**Comment by Bartvds** [comment]
Side note: I see you rejected an earlier pull request  #2 that offered grunt, partially because it was so verbose and the author killed the html test runner.

I remind you that a makefile doesn't work in windows, which goes a bit against the spirit of node.js and open web. If you want a new gruntfile with both a working jasmine-node as well as your original html runner and the licence + cat stuff you do in make, then you can easily cut it my from my branch.

I agree it's more code then 4 lines shellscript but it's also more capable, the issue #2 also had jshint, and you could also pull everything though jsbeautifier, concat and test everything in one go and on every platform.

**Comment by Bartvds** [comment]
I finished editing the [definitions file and compile test](https://github.com/Bartvds/jasmine-matchers/tree/typings/typings/jasmine-matchers)

I went a bit overboard while exploring `grunt` so with some plugin magic I can now generate the .test.ts file that's required for `DefinitelyTyped` directly from your unit tests and they even run again after compiling the now type-checked code back to javascript and also pass in `grunt_jasmine_node` just like your vanilla tests. 

There's more grunt then actual files but it's pretty neat as exercise, and as they pass the compiler and jasmine-node (after failing a _lot_ :) I'm hopeful they keep correct.

If you're interested you can give the [.d.ts](https://github.com/Bartvds/jasmine-matchers/blob/typings/typings/jasmine-matchers/jasmine-matchers.d.ts) a glance for approval.

As I spend some time in the code and unit tests I saved  logs [here](https://github.com/Bartvds/jasmine-matchers/blob/typings/pedantic.txt), but it's just minor stuff except the haveLength missing normal test case.

I think I'll be pushing this to [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) and it's [tsd](http://www.tsdpm.com/) package manager soon, let me know if you got some input.

(Again, there's no need to pull/merge this branch as it's a community addon)

**Comment by Bartvds** [comment]
I pushed the definitions so I'll close this issue.

**Comment by wolframkriesing** [comment]
oh shit, i didnt see all this going on here :(
I agree regarding grunt. as long as jasmine-matchers had been an internal tool the windows argument didnt beat mine, but now it definitely does. i am happy to apply grunt pull request ... sorry for my ignorance :)
