### ISSUE TITLE
Update jasmine-matchers NPM registry to v0.2.3

### ISSUE THREAD

**Issue by ghost** [uxebu/jasmine-matchers#7]
Guten tag Uxebu!

The latest version (v0.2.3) of jasmine-matchers is available on Github but [not available](https://www.npmjs.org/package/jasmine-matchers) at the NPM registry (still at 0.2.2).

May one of the maintainers please update the version there? Danke!

**Comment by wolframkriesing** [comment]
Thank you very much for that reminder. I just did that.

**Comment by ghost** [comment]
Excellent! Thanks Wolfram.
